/*
 * Auto-generated from: conlarge_xl_vela.npz
 * Do not edit by hand.
 *
 * Generated for Ethos-U direct driver invocation (no TFLM).
 * Assumes a single NPU command stream with no CPU fallback.
 */
#pragma once
#include <stddef.h>
#include <stdint.h>

// Base-pointer array length for Ethos-U
#define ETHOSU_MAX_REGIONS 8

// ---- Inputs ----
#define CONLARGE_XL_AMBIQHP_HBLRAM_SHARED_SRAM_256KB_INPUT0_REGION  1
#define CONLARGE_XL_AMBIQHP_HBLRAM_SHARED_SRAM_256KB_INPUT0_OFFSET  2112000
#define CONLARGE_XL_AMBIQHP_HBLRAM_SHARED_SRAM_256KB_INPUT0_SIZE    48000

// ---- Outputs ----
#define CONLARGE_XL_AMBIQHP_HBLRAM_SHARED_SRAM_256KB_OUTPUT0_REGION 1
#define CONLARGE_XL_AMBIQHP_HBLRAM_SHARED_SRAM_256KB_OUTPUT0_OFFSET 156464
#define CONLARGE_XL_AMBIQHP_HBLRAM_SHARED_SRAM_256KB_OUTPUT0_SIZE   153750

// ---- Variables ----

#define CONLARGE_XL_AMBIQHP_HBLRAM_SHARED_SRAM_256KB_SCRATCH_REGION 1
#define CONLARGE_XL_AMBIQHP_HBLRAM_SHARED_SRAM_256KB_SCRATCH_SIZE   2640000
#define CONLARGE_XL_AMBIQHP_HBLRAM_SHARED_SRAM_256KB_SCRATCH_FAST_REGION 0
#define CONLARGE_XL_AMBIQHP_HBLRAM_SHARED_SRAM_256KB_SCRATCH_FAST_SIZE   0
