/*
 * Auto-generated from: rnnoise_INT8_vela.npz
 * Do not edit by hand.
 *
 * Generated for Ethos-U direct driver invocation (no TFLM).
 * Assumes a single NPU command stream with no CPU fallback.
 */
#pragma once
#include <stddef.h>
#include <stdint.h>

// Base-pointer array length for Ethos-U
#define ETHOSU_MAX_REGIONS 8

// ---- Inputs ----
#define RNNOISE_INT8_INPUT0_REGION  1
#define RNNOISE_INT8_INPUT0_OFFSET  96
#define RNNOISE_INT8_INPUT0_SIZE    42
#define RNNOISE_INT8_INPUT1_REGION  1
#define RNNOISE_INT8_INPUT1_OFFSET  192
#define RNNOISE_INT8_INPUT1_SIZE    24
#define RNNOISE_INT8_INPUT2_REGION  1
#define RNNOISE_INT8_INPUT2_OFFSET  144
#define RNNOISE_INT8_INPUT2_SIZE    48
#define RNNOISE_INT8_INPUT3_REGION  1
#define RNNOISE_INT8_INPUT3_OFFSET  0
#define RNNOISE_INT8_INPUT3_SIZE    96

// ---- Outputs ----
#define RNNOISE_INT8_OUTPUT0_REGION 1
#define RNNOISE_INT8_OUTPUT0_OFFSET 0
#define RNNOISE_INT8_OUTPUT0_SIZE   96
#define RNNOISE_INT8_OUTPUT1_REGION 1
#define RNNOISE_INT8_OUTPUT1_OFFSET 96
#define RNNOISE_INT8_OUTPUT1_SIZE   22
#define RNNOISE_INT8_OUTPUT2_REGION 1
#define RNNOISE_INT8_OUTPUT2_OFFSET 240
#define RNNOISE_INT8_OUTPUT2_SIZE   48
#define RNNOISE_INT8_OUTPUT3_REGION 1
#define RNNOISE_INT8_OUTPUT3_OFFSET 208
#define RNNOISE_INT8_OUTPUT3_SIZE   24
#define RNNOISE_INT8_OUTPUT4_REGION 1
#define RNNOISE_INT8_OUTPUT4_OFFSET 192
#define RNNOISE_INT8_OUTPUT4_SIZE   1

// ---- Variables ----

#define RNNOISE_INT8_SCRATCH_REGION 1
#define RNNOISE_INT8_SCRATCH_SIZE   288
#define RNNOISE_INT8_SCRATCH_FAST_REGION 2
#define RNNOISE_INT8_SCRATCH_FAST_SIZE   704
