/*
 * Auto-generated from: efficientnet_lite0_s8_lg_vela.npz
 * Do not edit by hand.
 *
 * Generated for Ethos-U direct driver invocation (no TFLM).
 * Assumes a single NPU command stream with no CPU fallback.
 */
#pragma once
#include <stddef.h>
#include <stdint.h>

// Base-pointer array length for Ethos-U
#define ETHOSU_MAX_REGIONS 8

// ---- Inputs ----
#define EFFICIENTNET_LITE0_S8_LG_AMBIQLP_HBLRAM_SHARED_SRAM_256KB_INPUT0_REGION  1
#define EFFICIENTNET_LITE0_S8_LG_AMBIQLP_HBLRAM_SHARED_SRAM_256KB_INPUT0_OFFSET  250880
#define EFFICIENTNET_LITE0_S8_LG_AMBIQLP_HBLRAM_SHARED_SRAM_256KB_INPUT0_SIZE    150528

// ---- Outputs ----
#define EFFICIENTNET_LITE0_S8_LG_AMBIQLP_HBLRAM_SHARED_SRAM_256KB_OUTPUT0_REGION 1
#define EFFICIENTNET_LITE0_S8_LG_AMBIQLP_HBLRAM_SHARED_SRAM_256KB_OUTPUT0_OFFSET 0
#define EFFICIENTNET_LITE0_S8_LG_AMBIQLP_HBLRAM_SHARED_SRAM_256KB_OUTPUT0_SIZE   1000

// ---- Variables ----

#define EFFICIENTNET_LITE0_S8_LG_AMBIQLP_HBLRAM_SHARED_SRAM_256KB_SCRATCH_REGION 1
#define EFFICIENTNET_LITE0_S8_LG_AMBIQLP_HBLRAM_SHARED_SRAM_256KB_SCRATCH_SIZE   652288
#define EFFICIENTNET_LITE0_S8_LG_AMBIQLP_HBLRAM_SHARED_SRAM_256KB_SCRATCH_FAST_REGION 0
#define EFFICIENTNET_LITE0_S8_LG_AMBIQLP_HBLRAM_SHARED_SRAM_256KB_SCRATCH_FAST_SIZE   0
