#!/usr/bin/env python3
"""Run an example_models package on the Atomiq110 FPGA through the Ethos-U driver and store the hardware
output tensors as the package's ofm*.npy sidecars.

Flow per package: generate src/model_glue.h for the npu_ofm_dump AmbiqSuite example from the package's
*_meta.h / *_data.h, copy the package headers in (scratch regions moved to shared SRAM), build, start the
SWO viewer, flash, parse the hex dump, verify CRCs, write ofm<i>.npy and compare with the TFLite interpreter.

  python python/fpga_ofm_dump.py example_models/<model> [--build-only] [--ulp] [--pipeline]
"""
import argparse, os, re, shutil, signal, subprocess, sys, time, zlib
from pathlib import Path
import numpy as np

REPO = Path(__file__).resolve().parents[1]
EXAMPLE = Path.home() / "workspace/U85/ambiqsuite/boards/common6/examples/npu/npu_ofm_dump"
TOOLCHAIN = "/opt/arm-gnu-toolchain-14.3.rel1/bin"
JLINK_SN = "1160000024"
CTYPE_BYTES = {"int8_t": 1, "uint8_t": 1, "int16_t": 2, "int32_t": 4}


def parse_meta(meta: Path, upper: str):
    text = meta.read_text()
    ios = {"INPUT": {}, "OUTPUT": {}}
    for kind in ios:
        for m in re.finditer(rf"#define {upper}_{kind}(\d+)_(REGION|OFFSET|SIZE)\s+(\d+)", text):
            ios[kind].setdefault(int(m.group(1)), {})[m.group(2)] = int(m.group(3))
    for kind, d in ios.items():
        if sorted(d) != list(range(len(d))) or any(set(v) != {"REGION", "OFFSET", "SIZE"} for v in d.values()):
            raise SystemExit(f"{meta}: incomplete {kind} table: {d}")
    return ios["INPUT"], ios["OUTPUT"]



def stage(package: Path, ulp: bool):
    name = package.name; upper = name.upper()
    meta, data_h, buffers_c = package / f"{name}_meta.h", package / f"{name}_data.h", package / f"{name}_buffers.c"
    for p in (meta, data_h, buffers_c, package / f"{name}_cmd_data.h", package / f"{name}_weights.h", package / f"{name}_buffers.h"):
        if not p.is_file():
            raise SystemExit(f"missing {p}")
    inputs, outputs = parse_meta(meta, upper)
    text = data_h.read_text()
    arrays = {m.group(2): (m.group(1), int(m.group(3))) for m in re.finditer(rf"^const (\w+) ({re.escape(name)}_input(?:_\d+)?)\[(\d+)\]", text, re.M)}
    in_names = [f"{name}_input"] if (len(inputs) == 1 and f"{name}_input" in arrays) else [f"{name}_input_{i}" for i in range(len(inputs))]
    for i, n in enumerate(in_names):
        if n not in arrays:
            raise SystemExit(f"{data_h}: no array {n}")
        ctype, count = arrays[n]
        if count * CTYPE_BYTES[ctype] != inputs[i]["SIZE"]:
            raise SystemExit(f"input {i}: {n} is {count}x{ctype} = {count * CTYPE_BYTES[ctype]} B, meta says {inputs[i]['SIZE']} B")
    src = EXAMPLE / "src"
    for old in src.glob("*"):
        if old.name not in ("am_memory_map.h", "am_resources.c", "filelist.txt", "npu_ofm_dump.c"):
            old.unlink()
    for suffix in ("_cmd_data.h", "_weights.h", "_meta.h", "_buffers.h", "_data.h"):
        text = (package / f"{name}{suffix}").read_text()
        if suffix in ("_cmd_data.h", "_weights.h"):  # the driver needs the command stream and region bases 16-byte aligned
            text, n = re.subn(r"^((?:static\s+)?const\s+(?:uint8_t|int8_t|unsigned char)\s+\w+_(?:cmd_data|weights)\s*\[)", r"__attribute__((aligned(16))) \1", text, flags=re.M)
            if n != 1:
                raise SystemExit(f"{name}{suffix}: expected one array definition to align, found {n}")
        (src / f"{name}{suffix}").write_text(text)
    bc = buffers_c.read_text()
    bc2 = bc.replace("__attribute__((aligned(32))) static uint8_t", '__attribute__((section(".shared"), aligned(32))) static uint8_t')
    if bc2 == bc:
        raise SystemExit("buffers.c: no region arrays found to relocate")
    (src / "model_buffers.c").write_text(bc2)
    glue = ["/* generated by fpga_ofm_dump.py; do not edit */", "#pragma once", "#include <stdint.h>", "#include <stddef.h>",
            f'#include "{name}_cmd_data.h"', f'#include "{name}_meta.h"', f'#include "{name}_buffers.h"', f'#include "{name}_data.h"',
            f'#define MODEL_NAME "{name}"', f"#define MODEL_CMD_DATA {name}_cmd_data", f"#define MODEL_CMD_SIZE {name}_cmd_size",
            f"#define MODEL_N_INPUTS {len(inputs)}u", f"#define MODEL_N_OUTPUTS {len(outputs)}u",
            "typedef struct { int region; uint32_t offset; uint32_t size; const uint8_t *data; } model_io_t;",
            "static const model_io_t g_model_inputs[MODEL_N_INPUTS] = {"]
    glue += [f"    {{ {inputs[i]['REGION']}, {inputs[i]['OFFSET']}u, {inputs[i]['SIZE']}u, (const uint8_t *){in_names[i]} }}," for i in range(len(inputs))]
    glue += ["};", "static const model_io_t g_model_outputs[MODEL_N_OUTPUTS] = {"]
    glue += [f"    {{ {outputs[i]['REGION']}, {outputs[i]['OFFSET']}u, {outputs[i]['SIZE']}u, NULL }}," for i in range(len(outputs))]
    glue += ["};", ""]
    if ulp:
        glue.insert(2, "#define NPU_ULP_MODE 1")
    (src / "model_glue.h").write_text("\n".join(glue))
    return inputs, outputs


def build():
    env = dict(os.environ, PATH=f"{TOOLCHAIN}:{os.environ['PATH']}")
    subprocess.run(["make", "clean"], cwd=EXAMPLE / "gcc", env=env, check=True, capture_output=True)
    r = subprocess.run(["make", "-j8"], cwd=EXAMPLE / "gcc", env=env, capture_output=True, text=True)
    if r.returncode != 0 or not (EXAMPLE / "gcc/bin/npu_ofm_dump.bin").is_file():
        sys.stderr.write(r.stdout[-3000:] + r.stderr[-3000:]); raise SystemExit("build failed")
    return (EXAMPLE / "gcc/bin/npu_ofm_dump.bin").stat().st_size


def run_on_fpga(log: Path, timeout: float):
    if subprocess.run(["pgrep", "-f", "hpx profile|^JLinkExe|^JLinkSWOViewerCLExe"], capture_output=True).returncode == 0:
        raise SystemExit("J-Link probe busy (hpx/JLink process running); refusing to flash")
    log.unlink(missing_ok=True)
    viewer = subprocess.Popen(f"tail -f /dev/null | JLinkSWOViewerCLExe -device atomiq110 -swofreq 1000000 -itmport 0 -usb {JLINK_SN} -outputfile {log}",
                              shell=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, start_new_session=True)
    try:
        time.sleep(3)
        r = subprocess.run(["JLinkExe", "-USB", JLINK_SN, "-NoGui", "1", "-CommandFile", "flash.jlink"], cwd=EXAMPLE / "gcc", capture_output=True, text=True, timeout=180)
        if "O.K." not in r.stdout and "Download" not in r.stdout:
            sys.stderr.write(r.stdout[-1500:]); raise SystemExit("flash failed")
        t0 = time.time()
        while time.time() - t0 < timeout:
            if log.is_file() and "OFM_DONE" in log.read_text(errors="replace"):
                time.sleep(1); break
            time.sleep(1)
        else:
            raise SystemExit(f"timeout waiting for OFM_DONE in {log}")
    finally:
        os.killpg(os.getpgid(viewer.pid), signal.SIGTERM)
    return log.read_text(errors="replace")


def parse_dump(text: str, outputs):
    if "ERROR" in text:
        raise SystemExit("firmware reported: " + next(l for l in text.splitlines() if "ERROR" in l))
    m = re.search(r"OFM_DONE pass=(\d)", text)
    if not m or m.group(1) != "1":
        raise SystemExit("dump did not pass (non-deterministic or failed run)")
    blobs = {}
    lines = text.splitlines(); i = 0
    while i < len(lines):
        h = re.match(r"OFM (\d+) (\d+) (\d+) (\d+) ([0-9a-f]{8})$", lines[i].strip())
        if not h:
            i += 1; continue
        idx, size, crc = int(h.group(1)), int(h.group(4)), int(h.group(5), 16)
        hexs = []; i += 1
        while i < len(lines) and re.fullmatch(r"[0-9a-f]+", lines[i].strip()):
            hexs.append(lines[i].strip()); i += 1
        raw = bytes.fromhex("".join(hexs))
        if len(raw) != size or (zlib.crc32(raw) & 0xFFFFFFFF) != crc:
            raise SystemExit(f"output {idx}: got {len(raw)} B crc {zlib.crc32(raw) & 0xFFFFFFFF:08x}, firmware says {size} B crc {crc:08x}")
        blobs[idx] = raw
    if sorted(blobs) != list(range(len(outputs))):
        raise SystemExit(f"outputs parsed {sorted(blobs)}, expected {len(outputs)}")
    return blobs


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("package", type=Path); ap.add_argument("--build-only", action="store_true"); ap.add_argument("--ulp", action="store_true")
    ap.add_argument("--timeout", type=float, default=600); ap.add_argument("--pipeline", action="store_true", help="rerun run_vela_pipeline.py with the new sidecars (--skip-vela)")
    ap.add_argument("--system-config", default="AmbiqHP_SRAM"); ap.add_argument("--memory-mode", default="Dedicated_Sram_256KB")
    a = ap.parse_args(); package = a.package.resolve(); name = package.name
    inputs, outputs = stage(package, a.ulp)
    size = build(); print(f"built npu_ofm_dump for {name}: {size} B image, {len(inputs)} inputs, {len(outputs)} outputs")
    if a.build_only:
        return
    text = run_on_fpga(package / "fpga_ofm_dump.log", a.timeout)
    blobs = parse_dump(text, outputs)
    import tensorflow as tf
    it = tf.lite.Interpreter(model_path=str(package / f"{name}.tflite")); it.allocate_tensors()
    in_names = [f"{name}_input"] if len(it.get_input_details()) == 1 else [f"{name}_input_{i}" for i in range(len(it.get_input_details()))]
    for i, det in enumerate(it.get_input_details()):
        sidecar = package / f"ifm{i}.npy"
        if not sidecar.is_file():  # package predates the sidecars: recover the input from the compiled _data.h array
            arr_text = re.search(rf"{in_names[i]}\[\d+\] = \{{(.*?)\}};", (package / f"{name}_data.h").read_text(), re.S).group(1)
            vals = np.array([int(x) for x in arr_text.replace("\n", " ").split(",") if x.strip()], dtype=det["dtype"]).reshape(det["shape"])
            np.save(sidecar, vals); print(f"wrote {sidecar.name} from {name}_data.h")
        it.set_tensor(det["index"], np.load(sidecar))
    it.invoke()
    for i, det in enumerate(it.get_output_details()):
        arr = np.frombuffer(blobs[i], dtype=det["dtype"]).reshape(det["shape"])
        np.save(package / f"ofm{i}.npy", arr)
        ref = it.get_tensor(det["index"]).astype(np.int64); d = np.abs(arr.astype(np.int64) - ref)
        print(f"ofm{i}.npy {arr.shape} {arr.dtype}: vs interpreter max|diff|={d.max()} mismatches={(d > 0).sum()}/{d.size}")
    cpu = re.findall(r"RUN \d+ status=0 cpu_cycles=(\d+)", text)
    print(f"FPGA runs ok, CPU cycles per invoke: {cpu}")
    if a.pipeline:
        subprocess.run([sys.executable, str(REPO / "run_vela_pipeline.py"), str(package / f"{name}.tflite"), "--output-dir", str(package),
                        "--system-config", a.system_config, "--memory-mode", a.memory_mode, "--use-model-sidecar-npy", "--skip-vela"], check=True)


if __name__ == "__main__":
    main()
